import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import { useAuth } from "@/lib/AuthContext";
import { ArrowLeft, BadgeDollarSign, Save } from "lucide-react";

export default function BuyerProfile() {
  const { user } = useAuth();
  const [form,setForm]=useState({company:"",role_title:"",target_states:"TN",target_commodities:"",min_acres:"",max_acres:"",min_budget:"",max_budget:"",asset_preferences:"",notes:""});
  const [record,setRecord]=useState(null); const [saving,setSaving]=useState(false); const [saved,setSaved]=useState(false);
  useEffect(()=>{ if(!user?.id)return; (async()=>{ const rows=await base44.entities.BuyerProfile.filter({user_id:user.id},"-updated_date",1); if(rows?.[0]){setRecord(rows[0]); setForm(f=>({...f,...rows[0]}));}})();},[user?.id]);
  const set=(k,v)=>setForm(f=>({...f,[k]:v}));
  const save=async(e)=>{e.preventDefault(); if(!user?.id)return; setSaving(true); setSaved(false); const payload={user_id:user.id,name:user.name||"",email:user.email||"",company:form.company,role_title:form.role_title,target_states:form.target_states,target_commodities:form.target_commodities,min_acres:form.min_acres?Number(form.min_acres):null,max_acres:form.max_acres?Number(form.max_acres):null,min_budget:form.min_budget?Number(form.min_budget):null,max_budget:form.max_budget?Number(form.max_budget):null,asset_preferences:form.asset_preferences,notes:form.notes,active:true}; try{ if(record) {const r=await base44.entities.BuyerProfile.update(record.id,payload); setRecord(r);} else {const r=await base44.entities.BuyerProfile.create(payload); setRecord(r);} setSaved(true);} finally{setSaving(false)}};
  if(!user?.id)return <div className="min-h-screen p-10 text-center text-muted-foreground">Sign in to create a buyer profile.</div>;
  return <div className="min-h-screen bg-background"><header className="border-b border-border"><div className="mx-auto max-w-4xl px-6 py-4"><Link to="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft className="h-4 w-4"/>Back</Link></div></header><main className="mx-auto max-w-4xl px-6 py-10"><p className="text-xs uppercase tracking-[0.2em] text-muted-foreground">Buyer Network</p><h1 className="mt-2 font-heading text-3xl font-bold">Buyer Profile</h1><p className="mt-3 max-w-2xl text-sm text-muted-foreground">Tell S&S what you acquire so we can match you to quarry and mineral opportunities.</p><form onSubmit={save} className="mt-8 space-y-6 rounded-2xl border border-border bg-card p-6"><div className="grid gap-4 sm:grid-cols-2"><Field label="Company"><input className="input" value={form.company||""} onChange={e=>set("company",e.target.value)}/></Field><Field label="Role"><input className="input" value={form.role_title||""} onChange={e=>set("role_title",e.target.value)}/></Field><Field label="Target States"><input className="input" value={form.target_states||""} onChange={e=>set("target_states",e.target.value)} placeholder="TN, GA, AL"/></Field><Field label="Commodities"><input className="input" value={form.target_commodities||""} onChange={e=>set("target_commodities",e.target.value)} placeholder="Limestone, sand & gravel..."/></Field><Field label="Min Acres"><input className="input" inputMode="decimal" value={form.min_acres||""} onChange={e=>set("min_acres",e.target.value)}/></Field><Field label="Max Acres"><input className="input" inputMode="decimal" value={form.max_acres||""} onChange={e=>set("max_acres",e.target.value)}/></Field><Field label="Min Budget"><input className="input" inputMode="decimal" value={form.min_budget||""} onChange={e=>set("min_budget",e.target.value)}/></Field><Field label="Max Budget"><input className="input" inputMode="decimal" value={form.max_budget||""} onChange={e=>set("max_budget",e.target.value)}/></Field></div><Field label="Asset Preferences"><textarea className="input min-h-24" value={form.asset_preferences||""} onChange={e=>set("asset_preferences",e.target.value)} placeholder="Operating quarry, undeveloped potential, royalty interest..."/></Field><Field label="Notes"><textarea className="input min-h-24" value={form.notes||""} onChange={e=>set("notes",e.target.value)}/></Field><div className="flex items-center gap-3"><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-stone-900 px-5 py-3 font-semibold text-white disabled:opacity-50"><Save className="h-4 w-4"/>{saving?"Saving…":"Save Buyer Profile"}</button>{saved&&<span className="inline-flex items-center gap-1.5 text-sm font-medium text-emerald-700"><BadgeDollarSign className="h-4 w-4"/>Saved</span>}</div></form></main></div>;
}
function Field({label,children}){return <label className="block"><span className="mb-1.5 block text-xs font-semibold uppercase tracking-wider text-muted-foreground">{label}</span>{children}</label>}
