import React, { useEffect, useState } from "react";
import { base44 } from "@/api/base44Client";
import { useAuth } from "@/lib/AuthContext";
import { Bookmark, HandCoins, Send, Check } from "lucide-react";

export default function DealActions({ listing }) {
  const { user } = useAuth();
  const [saved,setSaved]=useState(false); const [open,setOpen]=useState(false); const [type,setType]=useState("Request Information"); const [amount,setAmount]=useState(""); const [terms,setTerms]=useState(""); const [financing,setFinancing]=useState(""); const [dd,setDd]=useState("30"); const [closing,setClosing]=useState("30"); const [sending,setSending]=useState(false); const [sent,setSent]=useState(false);
  useEffect(()=>{ if(!user?.id)return; (async()=>{const rows=await base44.entities.SavedOpportunity.filter({user_id:user.id,listing_id:listing.id},"-created_date",1); setSaved(Boolean(rows?.length));})();},[user?.id,listing.id]);
  const toggleSave=async()=>{if(!user?.id)return;if(saved){const rows=await base44.entities.SavedOpportunity.filter({user_id:user.id,listing_id:listing.id},"-created_date",1);if(rows?.[0])await base44.entities.SavedOpportunity.delete(rows[0].id);setSaved(false);}else{await base44.entities.SavedOpportunity.create({user_id:user.id,listing_id:listing.id,resource_name:listing.title,saved_at:new Date().toISOString()});setSaved(true);}};
  const submit=async(e)=>{e.preventDefault();if(!user?.id)return;setSending(true);try{let profile=[];try{profile=await base44.entities.BuyerProfile.filter({user_id:user.id},"-updated_date",1);}catch{};await base44.entities.DealInterest.create({user_id:user.id,buyer_email:user.email||"",buyer_company:profile?.[0]?.company||"",listing_id:listing.id,listing_title:listing.title,interest_type:type,offer_amount:amount?Number(amount):null,terms_summary:terms,financing_status:financing,due_diligence_days:dd?Number(dd):null,closing_days:closing?Number(closing):null,status:type==="Offer"?"Offer Submitted":"New",submitted_at:new Date().toISOString()});setSent(true);setOpen(false);}finally{setSending(false)}};
  if(!user?.id)return null;
  return <div className="mt-6 rounded-2xl border border-border bg-card p-5"><div className="flex flex-wrap gap-3"><button onClick={toggleSave} className="inline-flex items-center gap-2 rounded-xl border border-border px-4 py-2.5 text-sm font-semibold hover:bg-muted"><Bookmark className={`h-4 w-4 ${saved?"fill-current":""}`}/>{saved?"Saved":"Save Opportunity"}</button><button onClick={()=>setOpen(v=>!v)} className="inline-flex items-center gap-2 rounded-xl bg-stone-900 px-4 py-2.5 text-sm font-semibold text-white"><HandCoins className="h-4 w-4"/>Request Info / Make Offer</button>{sent&&<span className="inline-flex items-center gap-1.5 text-sm font-medium text-emerald-700"><Check className="h-4 w-4"/>Sent to S&S</span>}</div>{open&&<form onSubmit={submit} className="mt-5 space-y-4 border-t border-border pt-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Action"><select className="input" value={type} onChange={e=>setType(e.target.value)}><option>Request Information</option><option>Request Data Room</option><option>Indication of Interest</option><option>Offer</option></select></Field><Field label="Offer / Indicative Amount"><input className="input" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></Field><Field label="Financing Status"><input className="input" value={financing} onChange={e=>setFinancing(e.target.value)} placeholder="Cash, financed, proof of funds..."/></Field><Field label="Due Diligence Days"><input className="input" inputMode="numeric" value={dd} onChange={e=>setDd(e.target.value)}/></Field><Field label="Closing Days"><input className="input" inputMode="numeric" value={closing} onChange={e=>setClosing(e.target.value)}/></Field></div><Field label="Terms / Message"><textarea className="input min-h-24" value={terms} onChange={e=>setTerms(e.target.value)} placeholder="Price structure, contingencies, requested information, timing..."/></Field><button disabled={sending} className="inline-flex items-center gap-2 rounded-xl bg-sky-700 px-5 py-3 font-semibold text-white disabled:opacity-50"><Send className="h-4 w-4"/>{sending?"Sending…":"Send to S&S Deal Desk"}</button></form>}</div>;
}
function Field({label,children}){return <label className="block"><span className="mb-1.5 block text-xs font-semibold uppercase tracking-wider text-muted-foreground">{label}</span>{children}</label>}
